### PR TITLE
This PR contains changes to shutdown guest domains gracefully

### PR DESCRIPTION
**Pull request by al1img**

### CODE REVIEW

**Comment by lorc** [comment]
Seems reasonable. 

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
@arminn Could you please look at this PR? Especially regarding DomA.

**Comment by arminn** [comment]
Please do not merge this, till I check patch for DomA ( I'm pretty sure shutdown won't work for DomA).

**Comment by rshym** [comment]
Acked-by: Ruslan Shymkevych <<ruslan_shymkevych@epam.com>>

**Pull request merged**
