### PR TITLE
diplaymanager: remove obsolete installation path

### PR DESCRIPTION
**Pull request by oleksiimoisieiev**
Signed-off-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by oleksiimoisieiev** [comment]
@lorc  updated, added RB. Please review and merge.

**Comment by lorc** [comment]
@oleksiimoisieiev, you need to ask @iusyk, I believe

**Comment by iusyk** [comment]
> @oleksiimoisieiev, you need to ask @iusyk, I believe

Reviewed-by: Ihor Usyk "ihor_usyk@epam.com"

**Comment by lorc** [comment]
Well, I meant that Ihor merges PRs.

@iusyk, could you please merge this PR?

**Pull request merged**
