### PR TITLE
Fix misprint in RDEPENDS for some back-ends

### PR DESCRIPTION
**Pull request by rshym**
We have misprinted char in the name of RDEPENDS.
That results in absence of required run-time dependency.

### CODE REVIEW

**Comment by xakep-amatop** [comment]
`Acked-by: Mykola Kvach <mykola_kvach@epam.com>`

**Comment by lorc** [comment]
It would be nice to have some commit description

**Comment by rshym** [comment]
> It would be nice to have some commit description

Sorry. I have added a message.

**Comment by rshym** [comment]
`Ack`'s are added.
Tested by the compilation of the prod-devel.

**Pull request merged**
