### PR TITLE
Few fixes for core-image-weston.bbappend

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Review by lorc — COMMENTED** [review]
Do we have any other dependencies on OP-TEE?

I.e. will OP-TEE be built at all with this change?

**Comment by rshym** [comment]
For rcar - yes. It is included into the build for all rcar-based machines  here https://github.com/xen-troops/meta-renesas/blob/dunfell/meta-rcar-gen3/conf/machine/include/rcar_common.inc#L22

**Comment by rshym** [comment]
But for other platforms - it's an open question.
So, I think, maybe it's worth add 
```
EXTRA_IMAGEDEPENDS += " \
    optee-os \
"
```
to core-image-weston.bbappend

B ut I'm not sure.

**Comment by lorc** [comment]
Ah, okay. Let's hope that other platforms have similar deps somewhere.

Anyways, this is the correct change for this meta-layer.

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
PR is tested by the build of DomD:
;- prod-devel with IPK packages
- prod-minimal with RPM packages.
In both cases we have `tee-h3ulcb.*` placed into `deploy/images/h3ulcb/firmware` as expected.

Ready to be merged.

**Pull request merged**
