### PR TITLE
[V2] Yocto BSP v5.9 kirkstone + Linux DDK v1.15 + other misc things

### PR DESCRIPTION
**Pull request by otyshchenko1**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
This is V2 for https://github.com/xen-troops/meta-xt-common/pull/51 The WIP mask was lifted.

**Review by lorc — CHANGES_REQUESTED** [review]
Thank you for the fixes. I have no more comments:

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

Please note that I am marking this PR as "needs changes" to indicate that it requires extra actions before merging:

1. We need to branch out current `master` into `dunfell` branch
2. We need to merge all 3 PRs at once.

**Comment by lorc** [comment]
> Ok, thank you. I got it. One more patch has just appeared. https://github.com/xen-troops/meta-xt-common/commit/95797299bd9b7f501f2a97cf69bb961531a0d8c7 May I retain your A-b?

That commit says "The ivi shell configuration already exists in meta-renesas,
removing duplicate sections." What about other platforms? I am reminding you that this PR is for meta-xt-common, which is used by other vendors as well. 

I have a feeling that other platforms don't need changes removed by "weston-init: remove duplicated and unused ivi shell configuration" in the first place. So I am suggesting to rewrite commit summary and description to something like "weston-init: remove ivi shell configuration as it is platform-specific"

**Comment by otyshchenko1** [comment]
> > Ok, thank you. I got it. One more patch has just appeared. [9579729](https://github.com/xen-troops/meta-xt-common/commit/95797299bd9b7f501f2a97cf69bb961531a0d8c7) May I retain your A-b?
> 
> That commit says "The ivi shell configuration already exists in meta-renesas, removing duplicate sections." What about other platforms? I am reminding you that this PR is for meta-xt-common, which is used by other vendors as well.
> 
> I have a feeling that other platforms don't need changes removed by "weston-init: remove duplicated and unused ivi shell configuration" in the first place. So I am suggesting to rewrite commit summary and description to something like "weston-init: remove ivi shell configuration as it is platform-specific"

ok, already updated. Also please note that I have squashed this missing bit with https://github.com/xen-troops/meta-xt-common/pull/53/commits/66ce32d4d096d0f4e19c057d622722d463c09595:

diff --git a/meta-xt-driver-domain/recipes-extended/displaymanager/files/display-manager.service b/meta-xt-driver-domain/recipes-extended/displaymanager/files/display-manager.service
index 5c05d5e..0ea9b3d 100644
--- a/meta-xt-driver-domain/recipes-extended/displaymanager/files/display-manager.service
+++ b/meta-xt-driver-domain/recipes-extended/displaymanager/files/display-manager.service
@@ -4,6 +4,7 @@ Requires=dbus.service
 After=dbus.service weston.service
 
 [Service]
+Environment=WAYLAND_DISPLAY=wayland-1
 EnvironmentFile=/etc/default/weston
 Type=dbus
 BusName=com.epam.DisplayManager

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by otyshchenko1** [comment]
updated, added A-b, removed "88892e0 weston-init: remove ivi shell configuration as it is platform-specifiс" as it was discussed that it would need to be updated differently. Also updated https://github.com/xen-troops/meta-xt-common/pull/53/commits/bbffb6f62f7a92d32621335dea55dba11ed89391 as it was agreed internally.

**Review by lorc — APPROVED** [review]

**Pull request merged**
