### PR TITLE
Migrate to Renesas BSP v5.9.0 (and misc fixes)

### PR DESCRIPTION
**Pull request by otyshchenko1**

### CODE REVIEW

**Comment by otyshchenko1** [comment]
Please note, other required PRs are at: https://github.com/xen-troops/meta-xt-rcar/pull/35 https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/65

**Comment by rshym** [comment]
I'm not sure that test utils for 3D should be added to `meta-xt-common`. Maybe it's better to move them to `meta-xt-prod-devel-rcar`, especially considering that they require changes into platform-specific repo `meta-xt-rcar`.

**Comment by lorc** [comment]
I am worried that `meta-xt-common` depends on Renesas BSP version. We should decouple it. I believe, this is the right moment.

Also, @rshym made a good point about installing test applications to ALL our products.

**Comment by otyshchenko1** [comment]
> I'm not sure that test utils for 3D should be added to `meta-xt-common`. Maybe it's better to move them to `meta-xt-prod-devel-rcar`, especially considering that they require changes into platform-specific repo `meta-xt-rcar`.

I was thinking there was nothing rcar-specific in these apps, and the dependencies were quite generic as well. But I don't mind moving these apps to meta-xt-prod-devel-rcar, will do.

**Comment by otyshchenko1** [comment]
> I am worried that `meta-xt-common` depends on Renesas BSP version. We should decouple it. I believe, this is the right moment.

I assume you are speaking about Dom0's Linux origin? Although it is quite convenient to host and use the single Linux branch for all domains (Dom0, DomD and DomU), I tend to agree, it would be correct to use generic Linux here as there is nothing platform specific enabled in that domain (note that we *disable* all arches and other unneeded stuff in defconfig to make the resulting image thin). As it was discussed internally, we leave things as they are for now, and will update in due course.

**Comment by otyshchenko1** [comment]
Note for myself, I will squash "recipes-kernel: Switch Linux to latest "v5.10.41/rcar-5.1.4.1-xt0.1 branch" with "recipes-kernel: Update Linux for Renesas BSP v5.9.0", since the former just updates a branch.

**Comment by otyshchenko1** [comment]
I have just pushed new version according to the discussion https://github.com/xen-troops/meta-xt-common/pull/46/commits

**Pull request closed without merging**
