### PR TITLE
domd/domu: Install automation and debug applicaitons

### PR DESCRIPTION
**Pull request by svlad-90**
- Added expect, ltrace, strace, evtest tools to the DomU
- Added expect, ltrace, evtest tools to the DomD

#### Motivation:

We need the above-mentioned set of the tools in order to:
- Automate communication with the target device ( expect )
- Debug the Linux input events ( evtest )
- Debug system calls of our applications ( strace )
- Debug shared library calls of our applicaitons ( ltrace )

Tested on h3ulcb-4x2g-kf machine.

Reviewed-by: to be added
Signed-off-by: Vladyslav Goncharuk <vladyslav_goncharuk@epam.com>

### CODE REVIEW

**Comment by lorc** [comment]
Hi @svlad-90,

Thank you for the patch, but I am afraid, that `meta-xt-common` is not the right place for it. You see, this meta-layer is used across all our products, and for all platforms (not only Renesas).  Some of setups event don't have input devices, for instance. 

We don't want to add debugging tools to ALL of our products. So I am suggesting to make similar change to meta-layer for the product you use (`meta-xt-prod-devel-rcar` maybe?)

**Comment by svlad-90** [comment]
Hi @lorc, thanks for your feedback.

I agree with your point. For me, it is sufficient to apply the new change only to the 'meta-xt-prod-devel-rcar' product. My recent tasks are related only to it.

But I'm quite new to the yocto project, thus I want to clarify.

The [meta-xt-prod-devel-rcar](https://github.com/svlad-90/meta-xt-prod-devel-rcar) contains different "meta-" folders:

- meta-aos-tune
- meta-xt-domx-gen3
- meta-xt-prod-devel-rcar-control
- meta-xt-prod-devel-rcar-driver-domain

Does your suggestion mean, that I should create the following files inside the meta-xt-prod-devel-rcar?

- meta-xt-prod-devel-rcar/meta-xt-domu/recipes-extended/images/core-image-weston.bbappend
- meta-xt-prod-devel-rcar/meta-xt-driver-domain/recipes-extended/images/core-image-weston.bbappend

If not, please, clarify what would be the correct folders to place the changes in.

**Comment by lorc** [comment]
Well, in your case you can get away without modifying recipes at all.

I'd just  install those packages via `prod-devel-rcar.yaml` file. There is the handy section `domd_domu_conf`, which provides common `local.conf` entries for both DomD and DomU.

**Comment by svlad-90** [comment]
Hi @lorc, thanks for your feedback!

I'll try the proposed approach during the weekend.

If it will succeed, I will notify you here to close this PR.

**Comment by svlad-90** [comment]
Hi @lorc, I've tested your approach. It worked as expected.

Please, close this PR.

The new PR has been opened in the 'meta-xt-prod-devel-rcar' repo: https://github.com/xen-troops/meta-xt-prod-devel-rcar/pull/68

Once you'll have time - please, review it.

**Comment by lorc** [comment]
Closing, as requested.

BTW, you also can close your PRs.

**Pull request closed without merging**
